apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
#clientConnection:
#  kubeconfig: "/etc/kubernetes/scheduler.conf"
profiles:
  - schedulerName: limit-await-scheduler
    plugins:
      permit:
        enabled:
          - name: LimitAwait
